=== duongvanson/ICTUniversityTNU/XML/Tren Lop/hocba.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
        <xs:element name="HocBa">
        	<xs:complexType>
        		<xs:sequence>
        			<xs:element name="HoTen" type="xs:string"/>
        			<xs:element name="NgaySinh" type="xs:date"/>
        			<xs:element name="NamHoc">
        				<xs:complexType>
        					<xs:attribute name="number" type="xs:integer"/>
        					<xs:element name="Lop" type="xs:string"/>
        					<xs:element name="HocLuc" type="xs:string"/>
        					<xs:element name="HanhKiem" type="xs:string"/>
        					<xs:element name="GVCN" type="xs:string"/>
        					<xs:element name="Mons" minOccus="0" maxOccus="100">
        						<xs:complexType>
        							<xs:element name="Mon">
        								<xs:complexType>
        									<xs:attribute name="mamon" type="xs:string"/>
        									<xs:sequence>
        										<xs:element name="STT" type="xs:integer"/>
        										<xs:element name="TenMon" type="xs:string"/>
        										<xs:element name="HocKyI">
        											<xs:restriction base="float">
        												<xs:minExclusive value="0.0"/>
        												<xs:maxExclusive value="10.0"/>
        											</xs:restriction>
        										</xs:element>
        										<xs:element name="HocKyII">
        											<xs:restriction base="float">
        												<xs:minExclusive value="0.0"/>
        												<xs:maxExclusive value="10.0"/>
        											</xs:restriction>
        										</xs:element>
        										<xs:element name="CaNam">
        											<xs:restriction base="float">
        												<xs:minExclusive value="0.0"/>
        												<xs:maxExclusive value="10.0"/>
        											</xs:restriction>
        										</xs:element>
        									</xs:sequence>
        								</xs:complexType>
        							</xs:element>
        						</xs:complexType>
        					</xs:element>
        				</xs:complexType>
        			</xs:element>
        		</xs:sequence>
        	</xs:complexType>
        </xs:element>
</xs:schema>

=== duongvanson/ICTUniversityTNU/XML/Tren Lop/hocba.xml
<?xml version="1.0"?>
<!DOCTYPE HocBa SYSTEM "hocba.dtd">
<HocBa>
<!--<HocBa xmlns="hb"
				xmlns:xs="http://www.w3.org/2001/XMLSchema"
				xs:schemaLocation="hd C:\Users\dvson\Desktop\ICTUniversityTNU\XML\hocba.xsd">-->
	<HoTen>Duong Van Son</HoTen>
	<NgaySinh>03/01/1998</NgaySinh>
	<NamHoc number="2016">
		<Lop>KTPM</Lop>
		<HocLuc>TOT</HocLuc>
		<HanhKiem>TOT</HanhKiem>
		<GVCN>Nguyen Lan Oanh</GVCN>
		<Mons>
			<Mon mamon="m01">
				<STT>1</STT>
				<TenMon>XML</TenMon>
				<HocKyI>5</HocKyI>
				<HocKyII>5</HocKyII>
				<CaNam>5</CaNam>
			</Mon>
			<Mon mamon="m02">
				<STT>1</STT>
				<TenMon>Ung Dung</TenMon>
				<HocKyI>5</HocKyI>
				<HocKyII>5</HocKyII>
				<CaNam>5</CaNam>
			</Mon>
		</Mons>
	</NamHoc>
	<NamHoc number="2017">
		<Lop>KTPM</Lop>
		<HocLuc>TOT</HocLuc>
		<HanhKiem>TOT</HanhKiem>
		<GVCN>Nguyen Lan Oanh</GVCN>
		<Mons>
			<Mon mamon="m03">
				<STT>1</STT>
				<TenMon>XML</TenMon>
				<HocKyI>5</HocKyI>
				<HocKyII>5</HocKyII>
				<CaNam>5</CaNam>
			</Mon>
			<Mon mamon="m04">
				<STT>1</STT>
				<TenMon>Ung Dung</TenMon>
				<HocKyI>5</HocKyI>
				<HocKyII>5</HocKyII>
				<CaNam>5</CaNam>
			</Mon>
		</Mons>
	</NamHoc>
</HocBa>
