=== duongvanson/ICTUniversityTNU/XML/XML/XML/ThucHanh02/SieuThi.dtd
<!ELEMENT SieuThi (TenSieuThi, DiaChi, SoDT, Hang+ )>
<!ELEMENT TenSieuThi (#PCDATA)>
<!ELEMENT DiaChi (#PCDATA)>
<!ELEMENT SoDT (#PCDATA)>
<!ELEMENT Hang (TenHang, SoLuong, LoaiHang, DonGia)>
<!ELEMENT TenHang (#PCDATA)>
<!ELEMENT SoLuong (#PCDATA)>
<!ELEMENT LoaiHang (#PCDATA)>
<!ELEMENT DonGia (#PCDATA)>
<!ATTLIST Hang MaHang CDATA #IMPLIED>

=== duongvanson/ICTUniversityTNU/XML/XML/XML/ThucHanh01/SieuThi.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE SieuThi SYSTEM "..\ThucHanh02\SieuThi.dtd">
<SieuThi xmlns="http://tempuri.org/SieuThi.xsd">
  <TenSieuThi> DVS </TenSieuThi>
  <DiaChi> Thai Nguyen </DiaChi>
  <SoDT> 0354891155 </SoDT>
  <Hang MaHang ="mh01">
    <TenHang>Bimbim</TenHang>
    <SoLuong>190</SoLuong>
    <LoaiHang>Binh thuong</LoaiHang>
    <DonGia>5000</DonGia>
  </Hang>
  <Hang MaHang ="mh02">
    <TenHang>But chi</TenHang>
    <SoLuong>190</SoLuong>
    <LoaiHang>Binh thuong</LoaiHang>
    <DonGia>5000</DonGia>
  </Hang>
</SieuThi>
