=== duongvanson/ICTUniversityTNU/XML/XML/XMLDOM/dtd/HoaDon.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT Quyen (HoaDon*)>
<!ELEMENT HoaDon (Loai, Lien, VienThong, TenKhach, DiaChi, SDT, DichVuSuDung, TienChu, Ngay)>
<!ELEMENT Loai (#PCDATA)>
<!ELEMENT Lien (#PCDATA)>
<!ELEMENT VienThong (#PCDATA)>
<!ELEMENT TenKhach (#PCDATA)>
<!ELEMENT DiaChi (#PCDATA)>
<!ELEMENT SDT (#PCDATA)>
<!ELEMENT DichVuSuDung (DichVu*)>
<!ELEMENT TienChu (#PCDATA)>
<!ELEMENT Ngay (#PCDATA)>
<!ELEMENT TongTienDichVu (TThanhTien, TGhiChu)>
<!ELEMENT ThueVAT (VATThanhTien, VATGhiChu)>
<!ELEMENT TongTien (TongThanhTien, TongGhiChu)>
<!ELEMENT DichVu (DVThanhTien, DVGhiChu)>
<!ELEMENT TThanhTien (#PCDATA)>
<!ELEMENT TGhiChu (#PCDATA)>
<!ELEMENT VATThanhTien (#PCDATA)>
<!ELEMENT VATGhiChu (#PCDATA)>
<!ELEMENT TongThanhTien (#PCDATA)>
<!ELEMENT TongGhiChu (#PCDATA)>
<!ELEMENT DVThanhTien (#PCDATA)>
<!ELEMENT DVGhiChu (#PCDATA)>

=== duongvanson/ICTUniversityTNU/XML/XML/XMLDOM/xml/HoaDon.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Quyen SYSTEM "../dtd/HoaDon.dtd">
<Quyen>
  <HoaDon>
    <Loai>Hoa don dich vu vien thong</Loai>
    <Lien>Lien 2: mmm</Lien>
    <VienThong>ABC</VienThong>
    <TenKhach>A</TenKhach>
    <DiaChi>Ha Noi</DiaChi>
    <SDT>123465789</SDT>
    <DichVuSuDung>
      <DichVu>
        <DVThanhTien>dv 1</DVThanhTien>
        <DVGhiChu>null</DVGhiChu>
      </DichVu>
      <DichVu>
        <DVThanhTien>dv 2</DVThanhTien>
        <DVGhiChu>null</DVGhiChu>
      </DichVu>
    </DichVuSuDung>
    <TienChu>mot tram</TienChu>
    <Ngay>12/02/2015</Ngay>
  </HoaDon>
</Quyen>
